### ISSUE TITLE
Incorrect Python is being loaded on Linux machine

### ISSUE THREAD

**Issue by genert** [jvolkman/rules_pycross#109]
There is interesting issue with this module when building applications on Linux x86 machine.

On MacOS (arm) it works perfectly fine but running same build commands on Linux machine results the following error:

```
 → Traceback (most recent call last):
 →   File "/home/harri/.cache/bazel/_bazel_harri/205a8e836255ac622fdc257b4067107c/external/rules_pycross~/pycross/private/tools/raw_lock_resolver.py", line 548, in <module>
 →     main(parse_flags())
 →   File "/home/harri/.cache/bazel/_bazel_harri/205a8e836255ac622fdc257b4067107c/external/rules_pycross~/pycross/private/tools/raw_lock_resolver.py", line 538, in main
 →     result = resolve(args)
 →              ^^^^^^^^^^^^^
 →   File "/home/harri/.cache/bazel/_bazel_harri/205a8e836255ac622fdc257b4067107c/external/rules_pycross~/pycross/private/tools/raw_lock_resolver.py", line 356, in resolve
 →     with open(target_file, "r") as f:
 →          ^^^^^^^^^^^^^^^^^^^^^^
 → FileNotFoundError: [Errno 2] No such file or directory: '/home/harri/.cache/bazel/_bazel_harri/205a8e836255ac622fdc257b4067107c/external/rules_pycross~~environments~pycross_environments/python_3.11_aarch64-apple-darwin.json'
 → Loading: 58 packages loaded
 →     currently loading: 
Error: Traceback (most recent call last):
  /home/harri/workspace/xxx/Tiltfile:72:14: in <toplevel>
  /home/harri/workspace/xxx/Tiltfile:57:27: in build_service
Error in local: command "bazelisk query 'filter(\"^//\", buildfiles(deps(set(//service/cmd/service:load))))' --order_output=no" failed.
error: exit status 7
```

Why does pycross try to use darwin built Python on Linux?

Here is the setup.

MODULE.bazel
```
bazel_dep(name = "rules_pycross", version = "0.6.0")
bazel_dep(name = "rules_python_gazelle_plugin", version = "0.33.1")

# Override `rules_python_gazelle_plugin` until get merged.
# See https://github.com/bazelbuild/rules_python/pull/1976
git_override(
    module_name = "rules_python_gazelle_plugin",
    commit = "1cc0168b57fb88faa97711081edb071c6bd23260",
    remote = "https://github.com/wingsofovnia/rules_python",
    strip_prefix = "gazelle",
)

##################################################
## Python Setup
##################################################
python = use_extension("@rules_python//python/extensions:python.bzl", "python")
python.toolchain(
    is_default = True,
    python_version = "3.12.3",
)
use_repo(python, "python_versions")

# Load Python external dependencies into Bazel from Poetry lock
lock_import = use_extension("@rules_pycross//pycross/extensions:lock_import.bzl", "lock_import")
lock_import.import_poetry(
    lock_file = "//:poetry.lock",
    project_file = "//:pyproject.toml",
    repo = "pip",
)

lock_repos = use_extension("@rules_pycross//pycross/extensions:lock_repos.bzl", "lock_repos")
use_repo(lock_repos, "pip")

```

And root BUILD file
```
load("@bazel_gazelle//:def.bzl", "gazelle", "gazelle_binary")
load("@pip//:requirements.bzl", "all_whl_requirements")
load("@rules_python_gazelle_plugin//manifest:defs.bzl", "gazelle_python_manifest")
load("@rules_python_gazelle_plugin//modules_mapping:def.bzl", "modules_mapping")

package(
    default_applicable_licenses = ["//:license"],
)

gazelle_binary(
    name = "gazelle_binary",
    languages = [
        "@bazel_gazelle//language/go",  # Built-in rule from gazelle for Golang.
        "@bazel_gazelle//language/proto",  # Built-in rule from gazelle for Protos.
        "@rules_python_gazelle_plugin//python",  # Custom rule for Python.
    ],
    visibility = ["//visibility:public"],
)

# gazelle:python_root
# gazelle:map_kind py_library py_library @aspect_rules_py//py:defs.bzl
# gazelle:map_kind py_binary py_binary @aspect_rules_py//py:defs.bzl
# gazelle:map_kind py_test py_test @aspect_rules_py//py:defs.bzl
# gazelle:python_binary_naming_convention $package_name$
# gazelle:python_library_naming_convention $package_name$_lib
# gazelle:python_label_convention :$distribution_name$
# gazelle:python_label_normalization pep503
# gazelle:exclude .idea
# gazelle:exclude .github
# gazelle:exclude .vscode
# gazelle:exclude proto
# gazelle:go_naming_convention import_alias
# gazelle:resolve proto proto errorspb/errors.proto @com_github_cockroachdb_errors//errorspb:errorspb_proto
# gazelle:resolve proto go errorspb/errors.proto @com_github_cockroachdb_errors//errorspb
gazelle(
    name = "gazelle",
    gazelle = "//:gazelle_binary",
)

modules_mapping(
    name = "gazelle.metadata",
    tags = ["manual"],
    wheels = all_whl_requirements,
)

gazelle_python_manifest(
    name = "gazelle.mapping",
    modules_mapping = ":gazelle.metadata",
    pip_repository_name = "pip",
    tags = ["manual"],
)
```

**Comment by jvolkman** [comment]
So the Poetry lock file is platform-agnostic. Pycross turns that into a bunch of Bazel targets that support all of the platforms you're interested in. That set of platforms can be specified manually (like [here](https://github.com/jvolkman/rules_pycross/blob/325f7c3ecae324309ba988627f5d8516bdbcdd1d/e2e/bzlmod/MODULE.bazel#L53-L66)), but by default it's just all supported platforms for all versions of Python registered with `python.toolchain`, whether that be in your module or in a module that you consume.

So it's not actually trying to invoke the darwin Python, but rather read some information about it so that it can generate build targets. I'm not sure why it's failing to find that file; can you see what is contained in the directory `/home/harri/.cache/bazel/_bazel_harri/205a8e836255ac622fdc257b4067107c/external/rules_pycross~~environments~pycross_environments`?

**Comment by genert** [comment]
<img width="1515" alt="Screenshot 2024-07-31 at 11 26 28" src="https://github.com/user-attachments/assets/60343355-e57f-4543-95c3-83322690c57c">

**Comment by jvolkman** [comment]
Does `bazel clean --expunge` fix it?

**Comment by genert** [comment]
Doesn't work unfortunately :(
