### ISSUE TITLE
Adding h3 library fails on buildbuddy but I'm not sure why

### ISSUE THREAD

**Issue by blockjon-dd** [jvolkman/rules_pycross#127]
When we add h3 to our myproject.toml file and re-lock our python deps into bazel, things work locally.

Then, when I try to run them remotely on BuildBuddy, they fail:

```
WARNING: Build options --host_platform, --java_language_version, --java_runtime_version, and 3 more have changed, discarding analysis cache (this can be expensive, see https://bazel.build/advanced/performance/iteration-speed).
WARNING: --remote_upload_local_results is set, but the remote cache does not support uploading action results or the current account is not authorized to write local results to the remote cache.
INFO: Analyzed target //libraries/python/company/map_intelligence:unit_test_h3_helper_test (65 packages loaded, 7618 targets configured).
ERROR: /home/dev/.cache/bazel/_bazel_dev/155bb1574771dc607335fbe8110386b4/external/rules_pycross~~lock_repos~pip/_lock/BUILD.bazel:5:8: Building h3-4.1.2.tar.gz failed: (Exit 1): wheel_builder failed: error executing WheelBuild command (from target @@rules_pycross~~lock_repos~pip//_lock:_build_h3@4.1.2) bazel-out/aarch64-opt-exec-ST-3b7d3a520a33/bin/external/rules_pycross~/pycross/private/tools/wheel_builder --sdist external/rules_pycross~~lock_repos~pypi_h3-4.1.2.tar.gz_505344f0/file/h3-4.1.2.tar.gz ... (remaining 16 arguments skipped)
/buildbuddy-execroot/bazel-out/aarch64-opt-exec-ST-3b7d3a520a33/bin/external/rules_pycross~/pycross/private/tools/wheel_builder.runfiles/_main/../rules_pycross~/pycross/private/tools/wheel_builder.py:394: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  f.extractall(sdist_dir)

Traceback (most recent call last):
  File "/buildbuddy-execroot/bazel-out/aarch64-opt-exec-ST-3b7d3a520a33/bin/external/rules_pycross~/pycross/private/tools/wheel_builder.runfiles/_main/../rules_pycross~/pycross/private/tools/wheel_builder.py", line 668, in build_wheel
    wheel_file = builder.build(
                 ^^^^^^^^^^^^^^
  File "/buildbuddy-execroot/bazel-out/aarch64-opt-exec-ST-3b7d3a520a33/bin/external/rules_pycross~/pycross/private/tools/wheel_builder.runfiles/rules_pycross~~pycross~rules_pycross_internal/deps/build@1.0.3/site-packages/build/__init__.py", line 298, in build
    return self._call_backend(f'build_{distribution}', output_directory, config_settings, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/buildbuddy-execroot/bazel-out/aarch64-opt-exec-ST-3b7d3a520a33/bin/external/rules_pycross~/pycross/private/tools/wheel_builder.runfiles/rules_pycross~~pycross~rules_pycross_internal/deps/build@1.0.3/site-packages/build/__init__.py", line 344, in _call_backend
    with self._handle_backend(hook_name):
  File "/buildbuddy-execroot/bazel-out/aarch64-opt-exec-ST-3b7d3a520a33/bin/external/rules_pycross~/pycross/private/tools/wheel_builder.runfiles/rules_python~~python~python_3_12_x86_64-unknown-linux-gnu/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/buildbuddy-execroot/bazel-out/aarch64-opt-exec-ST-3b7d3a520a33/bin/external/rules_pycross~/pycross/private/tools/wheel_builder.runfiles/rules_pycross~~pycross~rules_pycross_internal/deps/build@1.0.3/site-packages/build/__init__.py", line 354, in _handle_backend
    raise BuildBackendException(
build._exceptions.BuildBackendException: Backend 'scikit_build_core.build' is not available.

ERROR Backend 'scikit_build_core.build' is not available.
Target //libraries/python/company/map_intelligence:unit_test_h3_helper_test failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /home/dev/.cache/bazel/_bazel_dev/155bb1574771dc607335fbe8110386b4/external/rules_pycross~~lock_repos~pip/_lock/BUILD.bazel:5:8 Installing h3-4.1.2.whl failed: (Exit 1): wheel_builder failed: error executing WheelBuild command (from target @@rules_pycross~~lock_repos~pip//_lock:_build_h3@4.1.2) bazel-out/aarch64-opt-exec-ST-3b7d3a520a33/bin/external/rules_pycross~/pycross/private/tools/wheel_builder --sdist external/rules_pycross~~lock_repos~pypi_h3-4.1.2.tar.gz_505344f0/file/h3-4.1.2.tar.gz ... (remaining 16 arguments skipped)
INFO: Elapsed time: 12.453s, Critical Path: 11.26s
INFO: 5 processes: 3 internal, 2 remote.
ERROR: Build did NOT complete successfully
```

What might the problem be?

I found [this thread](https://github.com/jvolkman/rules_pycross/issues/101#issuecomment-2137650231) which suggests something like this:

```
lock_import.package(
    name = "h3",
    always_build = True,
    build_dependencies = [
        "setuptools",
        "wheel",
    ],
    repo = "pip",
)

lock_import.package(
    name = "scikit-build-core",
    always_build = True,
    build_dependencies = [
        "setuptools",
        "wheel",
    ],
    repo = "pip",
)
```

but this does not help.

One potential clue is that in the error message I posted above, I see `x86_64` as a substring. However, we are running on arm64 in our BuildBuddy.

**Comment by blockjon-dd** [comment]
I also added these to the myproject.toml but it did not help:
```
    "h3>=4.1.2",
    "scikit-build-core>=0.10.7",
```

**Comment by mpiro** [comment]
i think we might need `cmake` as well?

**Comment by mpiro** [comment]
i tried some of that in our branch too...we might try using version a h3 that doesn't depend on `scikit-build-core` for now. `3.7.4` is the lastest version that doesn't depend on it it looks like

**Comment by blockjon-dd** [comment]
> i tried some of that in our branch too...we might try using version a h3 that doesn't depend on `scikit-build-core` for now. Looks like `3.7.4` is the lastest version that doesn't depend on it

actually this did not work either.

**Comment by blockjon-dd** [comment]
Switching from pdm to poetry seems to resolve the problem

**Comment by blockjon-dd** [comment]
Closing bc my problems went away as soon as i switched to poetry
