### ISSUE TITLE
`Unknown platform: aarch64-apple-darwin-freethreaded` with Bazel 8.0.0rc4

### ISSUE THREAD

**Issue by lalten** [jvolkman/rules_pycross#128]
I'm adding Bazel 8 to the rules_appimage CI and the rules_pycross compatibility test fails in Bazel 8: https://github.com/lalten/rules_appimage/actions/runs/12119608705/job/33786541460?pr=253
```
INFO: Repository rules_pycross++environments+pycross_environments instantiated at:
  <builtin>: in <toplevel>
Repository rule pycross_environments_repo defined at:
  /home/runner/.cache/bazel/_bazel_runner/98a5b15d41eaf418ed0fd79d24a54d98/external/rules_pycross+/pycross/private/toolchain_helpers.bzl:430:[44](https://github.com/lalten/rules_appimage/actions/runs/12119608705/job/33786541460?pr=253#step:6:45): in <toplevel>
ERROR: /home/runner/.cache/bazel/_bazel_runner/98a5b15d41eaf418ed0fd79d24a54d98/external/rules_pycross+/pycross/private/toolchain_helpers.bzl:54:9: An error occurred during the fetch of repository 'rules_pycross++environments+pycross_environments':
   Traceback (most recent call last):
	File "/home/runner/.cache/bazel/_bazel_runner/98a5b15d41eaf418ed0fd79d24a54d98/external/rules_pycross+/pycross/private/toolchain_helpers.bzl", line 391, column 50, in _pycross_environment_repo_impl
		computed_environments = _compute_environments(
	File "/home/runner/.cache/bazel/_bazel_runner/98a5b15d41eaf418ed0fd79d24a54d98/external/rules_pycross+/pycross/private/toolchain_helpers.bzl", line 100, column [47](https://github.com/lalten/rules_appimage/actions/runs/12119608705/job/33786541460?pr=253#step:6:48), in _compute_environments
		env_platforms = _get_env_platforms(target_platform, glibc_version, macos_version)
	File "/home/runner/.cache/bazel/_bazel_runner/98a5b15d41eaf418ed0fd79d24a54d98/external/rules_pycross+/pycross/private/toolchain_helpers.bzl", line 54, column 9, in _get_env_platforms
		fail("Unknown platform: {}".format(py_platform))
Error in fail: Unknown platform: aarch64-apple-darwin-freethreaded
```

The specific run is for Bazel 8.0.0rc4 on ubuntu-latest with Bzlmod active.

I don't test rules_pycross compatibility with Workspace or Macos, so I can't say if that would work.

Any idea what would cause this?

repro:
```sh
git clone https://github.com/lalten/rules_appimage.git
cd rules_appimage
USE_BAZEL_VERSION=8.0.0rc4 bazel test //...
```

**Comment by lalten** [comment]
It seems to be related to https://github.com/indygreg/python-build-standalone/pull/326. rules_appimage uses Python 3.13 by default.

**Comment by betaboon** [comment]
@lalten i see you updated to `rules_pycross==0.7.1`.

i just tried your repro with that version, and it now seems to work.

so i assume this issue is resolved?

**Comment by lalten** [comment]
Iirc the issue was only apparent when using Python 3.13. I've reduced the default to 3.12 in the MODULE.bazel to work around for now.

**Comment by blockjon-dd** [comment]
@lalten does my PR https://github.com/jvolkman/rules_pycross/pull/151 fix your problem?
