### ISSUE TITLE
sdist fails for linux wheel on mac

### ISSUE THREAD

**Issue by codebreach** [jvolkman/rules_pycross#32]
OpenAI only publishes source on pypi

the following rules are generated
```

    _openai_0_23_0_deps = [
        ":numpy_1.24.2",
        ":openpyxl_3.1.1",
        ":pandas_1.4.3",
        ":pandas_stubs_1.5.3.230214",
        ":requests_2.28.1",
        ":tqdm_4.64.0",
        ":typing_extensions_4.5.0",
    ]

    _openai_0_23_0_build_deps = [
        ":setuptools_67.4.0",
        ":wheel_0.38.4",
    ]

    pycross_wheel_build(
        name = "_build_openai_0.23.0",
        sdist = "@lock_sdist_openai_0.23.0//file",
        target_environment = _target,
        deps = _openai_0_23_0_deps + _openai_0_23_0_build_deps,
        tags = ["manual"],
    )

    pycross_wheel_library(
        name = "openai_0.23.0",
        deps = _openai_0_23_0_deps,
        wheel = ":_build_openai_0.23.0",
    )

```

(can be replicated by adding openai using poetry and generating lock)

when trying to build the wheel for linux i get following failure
```
bazelisk build --@io_bazel_rules_go//go/config:pure --platforms @io_bazel_rules_go//go/toolchain:linux_amd64 //utils/pypi:openai_0.23.0
```

failure:
```
INFO: Analyzed target //utils/pypi:openai_0.23.0 (80 packages loaded, 9846 targets configured).
INFO: Found 1 target...
ERROR: /Users/madhav/Code/sdroot/mr-ping/utils/pypi/BUILD:5:8: Building openai-0.23.0.tar.gz failed: (Exit 1): wheel_builder failed: error executing command bazel-out/host/bin/external/jvolkman_rules_pycross/pycross/private/tools/wheel_builder --sdist external/lock_sdist_openai_0.23.0/file/openai-0.23.0.tar.gz --sysconfig-vars ... (remaining 47 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_madhav/2034f50a8630c7b3af59aa011432cbea/sandbox/darwin-sandbox/89/execroot/__main__/bazel-out/host/bin/external/jvolkman_rules_pycross/pycross/private/tools/wheel_builder.runfiles/jvolkman_rules_pycross/pycross/private/tools/wheel_builder.py", line 704, in <module>
    app.run(main_wrapper, flags_parser=parse_flags)
  File "/private/var/tmp/_bazel_madhav/2034f50a8630c7b3af59aa011432cbea/sandbox/darwin-sandbox/89/execroot/__main__/bazel-out/host/bin/external/jvolkman_rules_pycross/pycross/private/tools/wheel_builder.runfiles/rules_pycross_pypi_deps_absl_py/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/private/var/tmp/_bazel_madhav/2034f50a8630c7b3af59aa011432cbea/sandbox/darwin-sandbox/89/execroot/__main__/bazel-out/host/bin/external/jvolkman_rules_pycross/pycross/private/tools/wheel_builder.runfiles/rules_pycross_pypi_deps_absl_py/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/private/var/tmp/_bazel_madhav/2034f50a8630c7b3af59aa011432cbea/sandbox/darwin-sandbox/89/execroot/__main__/bazel-out/host/bin/external/jvolkman_rules_pycross/pycross/private/tools/wheel_builder.runfiles/jvolkman_rules_pycross/pycross/private/tools/wheel_builder.py", line 693, in main_wrapper
    main(args, _temp_dir, _is_debug)
  File "/private/var/tmp/_bazel_madhav/2034f50a8630c7b3af59aa011432cbea/sandbox/darwin-sandbox/89/execroot/__main__/bazel-out/host/bin/external/jvolkman_rules_pycross/pycross/private/tools/wheel_builder.runfiles/jvolkman_rules_pycross/pycross/private/tools/wheel_builder.py", line 564, in main
    target_sysconfig_vars = get_target_sysconfig(
  File "/private/var/tmp/_bazel_madhav/2034f50a8630c7b3af59aa011432cbea/sandbox/darwin-sandbox/89/execroot/__main__/bazel-out/host/bin/external/jvolkman_rules_pycross/pycross/private/tools/wheel_builder.runfiles/jvolkman_rules_pycross/pycross/private/tools/wheel_builder.py", line 127, in get_target_sysconfig
    vars_json = subprocess.check_output(args=query_args)
  File "/private/var/tmp/_bazel_madhav/2034f50a8630c7b3af59aa011432cbea/execroot/__main__/external/python3_9_aarch64-apple-darwin/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/private/var/tmp/_bazel_madhav/2034f50a8630c7b3af59aa011432cbea/execroot/__main__/external/python3_9_aarch64-apple-darwin/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/private/var/tmp/_bazel_madhav/2034f50a8630c7b3af59aa011432cbea/execroot/__main__/external/python3_9_aarch64-apple-darwin/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/private/var/tmp/_bazel_madhav/2034f50a8630c7b3af59aa011432cbea/execroot/__main__/external/python3_9_aarch64-apple-darwin/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: PosixPath('external/python3_9_x86_64-unknown-linux-gnu/bin/python3')
----------------
Note: The failure of target @jvolkman_rules_pycross//pycross/private/tools:wheel_builder (with exit code 1) may have been caused by the fact that it is running under Python 3 instead of Python 2. Examine the error to determine if that appears to be the problem. Since this target is built in the host configuration, the only way to change its version is to set --host_force_python=PY2, which affects the entire build.

If this error started occurring in Bazel 0.27 and later, it may be because the Python toolchain now enforces that targets analyzed as PY2 and PY3 run under a Python 2 and Python 3 interpreter, respectively. See https://github.com/bazelbuild/bazel/issues/7899 for more information.
----------------
Target //utils/pypi:openai_0.23.0 failed to build
```

seems like a linux python executable is trying to be executed but on a mac, is this expected? any ideas?

**Comment by jvolkman** [comment]
If you're trying to build a wheel cross-platform you'll need to setup the cross-platform toolchains. 

e.g. https://github.com/jvolkman/rules_pycross/blob/main/examples/crossenv/BUILD.bazel#L77-L90
and https://github.com/jvolkman/rules_pycross/blob/main/examples/crossenv/WORKSPACE#L90-L95

**Comment by codebreach** [comment]
So I already had the toolchains set up and even added flag `--platforms //:linux_x86_64` to the build step like documented [here](https://github.com/jvolkman/rules_pycross/blob/main/examples/crossenv/README.md?plain=1#L8)

but still get the same error:

```
bazelisk build --@io_bazel_rules_go//go/config:pure --platforms @io_bazel_rules_go//go/toolchain:linux_amd64 --platforms //:linux_x86_64 //utils/pypi:openai_0.23.0
INFO: Build option --stamp has changed, discarding analysis cache.
INFO: Analyzed target //utils/pypi:openai_0.23.0 (0 packages loaded, 9854 targets configured).
INFO: Found 1 target...
ERROR: /Users/madhav/Code/sdroot/mr-ping/utils/pypi/BUILD:5:8: Building openai-0.23.0.tar.gz failed: (Exit 1): wheel_builder failed: error executing command bazel-out/host/bin/external/jvolkman_rules_pycross/pycross/private/tools/wheel_builder --sdist external/lock_sdist_openai_0.23.0/file/openai-0.23.0.tar.gz --sysconfig-vars ... (remaining 47 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_madhav/2034f50a8630c7b3af59aa011432cbea/sandbox/darwin-sandbox/618/execroot/__main__/bazel-out/host/bin/external/jvolkman_rules_pycross/pycross/private/tools/wheel_builder.runfiles/jvolkman_rules_pycross/pycross/private/tools/wheel_builder.py", line 704, in <module>
    app.run(main_wrapper, flags_parser=parse_flags)
  File "/private/var/tmp/_bazel_madhav/2034f50a8630c7b3af59aa011432cbea/sandbox/darwin-sandbox/618/execroot/__main__/bazel-out/host/bin/external/jvolkman_rules_pycross/pycross/private/tools/wheel_builder.runfiles/rules_pycross_pypi_deps_absl_py/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/private/var/tmp/_bazel_madhav/2034f50a8630c7b3af59aa011432cbea/sandbox/darwin-sandbox/618/execroot/__main__/bazel-out/host/bin/external/jvolkman_rules_pycross/pycross/private/tools/wheel_builder.runfiles/rules_pycross_pypi_deps_absl_py/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/private/var/tmp/_bazel_madhav/2034f50a8630c7b3af59aa011432cbea/sandbox/darwin-sandbox/618/execroot/__main__/bazel-out/host/bin/external/jvolkman_rules_pycross/pycross/private/tools/wheel_builder.runfiles/jvolkman_rules_pycross/pycross/private/tools/wheel_builder.py", line 693, in main_wrapper
    main(args, _temp_dir, _is_debug)
  File "/private/var/tmp/_bazel_madhav/2034f50a8630c7b3af59aa011432cbea/sandbox/darwin-sandbox/618/execroot/__main__/bazel-out/host/bin/external/jvolkman_rules_pycross/pycross/private/tools/wheel_builder.runfiles/jvolkman_rules_pycross/pycross/private/tools/wheel_builder.py", line 564, in main
    target_sysconfig_vars = get_target_sysconfig(
  File "/private/var/tmp/_bazel_madhav/2034f50a8630c7b3af59aa011432cbea/sandbox/darwin-sandbox/618/execroot/__main__/bazel-out/host/bin/external/jvolkman_rules_pycross/pycross/private/tools/wheel_builder.runfiles/jvolkman_rules_pycross/pycross/private/tools/wheel_builder.py", line 127, in get_target_sysconfig
    vars_json = subprocess.check_output(args=query_args)
  File "/private/var/tmp/_bazel_madhav/2034f50a8630c7b3af59aa011432cbea/execroot/__main__/external/python3_9_aarch64-apple-darwin/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/private/var/tmp/_bazel_madhav/2034f50a8630c7b3af59aa011432cbea/execroot/__main__/external/python3_9_aarch64-apple-darwin/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/private/var/tmp/_bazel_madhav/2034f50a8630c7b3af59aa011432cbea/execroot/__main__/external/python3_9_aarch64-apple-darwin/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/private/var/tmp/_bazel_madhav/2034f50a8630c7b3af59aa011432cbea/execroot/__main__/external/python3_9_aarch64-apple-darwin/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: PosixPath('external/python3_9_x86_64-unknown-linux-gnu/bin/python3')
----------------
Note: The failure of target @jvolkman_rules_pycross//pycross/private/tools:wheel_builder (with exit code 1) may have been caused by the fact that it is running under Python 3 instead of Python 2. Examine the error to determine if that appears to be the problem. Since this target is built in the host configuration, the only way to change its version is to set --host_force_python=PY2, which affects the entire build.

If this error started occurring in Bazel 0.27 and later, it may be because the Python toolchain now enforces that targets analyzed as PY2 and PY3 run under a Python 2 and Python 3 interpreter, respectively. See https://github.com/bazelbuild/bazel/issues/7899 for more information.
----------------
Target //utils/pypi:openai_0.23.0 failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /Users/madhav/Code/sdroot/mr-ping/utils/pypi/BUILD:5:8 Installing openai-0.23.0.whl failed: (Exit 1): wheel_builder failed: error executing command bazel-out/host/bin/external/jvolkman_rules_pycross/pycross/private/tools/wheel_builder --sdist external/lock_sdist_openai_0.23.0/file/openai-0.23.0.tar.gz --sysconfig-vars ... (remaining 47 arguments skipped)
```

**Comment by codebreach** [comment]
FWIW I was able to "workaround" by using `openai 0.27.2` which does publish wheels

**Comment by jvolkman** [comment]
What do your toolchain configurations look like? And what version of Bazel are you using? You may need to use bazel's toolchain resolution debug.

**Comment by codebreach** [comment]
Tool chain config is copied verbatim from the example. 

Let me run with toolchain debug and share the output with you here.

**Comment by jvolkman** [comment]
Closing; please re-open if this is still an issue.
