### ISSUE TITLE
Lock generator fails

### ISSUE THREAD

**Issue by rparme** [jvolkman/rules_pycross#35]
Hi, 

Before anything, thank you for this initiative, that is great work.

I'm trying to use the example provided in `rules_pycross/examples/poetry`: I clone the project, navigate to the aforesaid folder and then run:
* `bazel run :update_example_lock`. It works
* I delete `poetry.lock` and run `poetry install`. This generate a new `poetry.lock`, different from the one provided. I'm running `poetry 1.4.2`.
*  `bazel run :update_example_lock`. Now it fails with:
  ```
  ERROR: /Users/rparme642/workspace/sandbox/rules_pycross/examples/poetry/BUILD.bazel:83:18: Action example_lock.bzl failed: (Exit 1): bzl_lock_generator failed: error executing command bazel-out/host/bin/external/jvolkman_rules_pycross/pycross/private/tools/bzl_lock_generator --lock-model-file bazel-out/darwin_arm64-fastbuild/bin/example_lock_model.json --repo-prefix example_lock ... (remaining 61 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_rparme642/411f21b03d7ae690c53b656d45a85f57/sandbox/darwin-sandbox/50/execroot/jvolkman_rules_pycross_example/bazel-out/host/bin/external/jvolkman_rules_pycross/pycross/private/tools/bzl_lock_generator.runfiles/jvolkman_rules_pycross/pycross/private/tools/bzl_lock_generator.py", line 986, in <module>
    app.run(main, flags_parser=parse_flags)
  File "/private/var/tmp/_bazel_rparme642/411f21b03d7ae690c53b656d45a85f57/sandbox/darwin-sandbox/50/execroot/jvolkman_rules_pycross_example/bazel-out/host/bin/external/jvolkman_rules_pycross/pycross/private/tools/bzl_lock_generator.runfiles/rules_pycross_pypi_deps_absl_py/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/private/var/tmp/_bazel_rparme642/411f21b03d7ae690c53b656d45a85f57/sandbox/darwin-sandbox/50/execroot/jvolkman_rules_pycross_example/bazel-out/host/bin/external/jvolkman_rules_pycross/pycross/private/tools/bzl_lock_generator.runfiles/rules_pycross_pypi_deps_absl_py/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/private/var/tmp/_bazel_rparme642/411f21b03d7ae690c53b656d45a85f57/sandbox/darwin-sandbox/50/execroot/jvolkman_rules_pycross_example/bazel-out/host/bin/external/jvolkman_rules_pycross/pycross/private/tools/bzl_lock_generator.runfiles/jvolkman_rules_pycross/pycross/private/tools/bzl_lock_generator.py", line 737, in main
    resolved = resolve_single_version(
  File "/private/var/tmp/_bazel_rparme642/411f21b03d7ae690c53b656d45a85f57/sandbox/darwin-sandbox/50/execroot/jvolkman_rules_pycross_example/bazel-out/host/bin/external/jvolkman_rules_pycross/pycross/private/tools/bzl_lock_generator.runfiles/jvolkman_rules_pycross/pycross/private/tools/bzl_lock_generator.py", line 614, in resolve_single_version
    raise Exception(f'{attr_name} entry "{name}" matches no packages')
Exception: always_build_packages entry "pbr@5.10.0" matches no packages
----------------
Note: The failure of target @jvolkman_rules_pycross//pycross/private/tools:bzl_lock_generator (with exit code 1) may have been caused by the fact that it is running under Python 3 instead of Python 2. Examine the error to determine if that appears to be the problem. Since this target is built in the host configuration, the only way to change its version is to set --host_force_python=PY2, which affects the entire build.

If this error started occurring in Bazel 0.27 and later, it may be because the Python toolchain now enforces that targets analyzed as PY2 and PY3 run under a Python 2 and Python 3 interpreter, respectively. See https://github.com/bazelbuild/bazel/issues/7899 for more information.
  ```
Am I doing anything wrong? I'm not sure I fully understand the issue described by the error message.

**Comment by jvolkman** [comment]
[This line](https://github.com/jvolkman/rules_pycross/blob/main/examples/poetry/BUILD.bazel#L87) is referring to `pbr==5.10.0` and re-running `poetry install` probably picked a new version of that package. If you change the `5.10.0` to whatever the new version is, or remove the version leave just `pbr`, this error should go away.

**Comment by rparme** [comment]
Indeed! Sorry, it's a none issue. 
Thank you for your quick answer.
